load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["token.go"],
    importpath = "github.com/rafaelzarate/monkey-lang-interpreter/token",
    visibility = ["//visibility:public"],
)
