load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["ast.go"],
    importpath = "github.com/rafaelzarate/monkey-lang-interpreter/ast",
    visibility = ["//visibility:public"],
    deps = ["//token:go_default_library"],
)
